# Generated by Django 5.2.1 on 2025-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_date', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(max_length=255, null=True)),
                ('Order_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Name', models.TextField(blank=True, null=True)),
                ('Mobile_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Item_Details', models.TextField(blank=True, null=True)),
                ('Item_Description', models.TextField(blank=True, null=True)),
                ('Sub_Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Delivery_Charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GST', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Grand_Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Pay_Mode', models.CharField(blank=True, max_length=100, null=True)),
                ('Delivery_Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Station', models.CharField(blank=True, max_length=100, null=True)),
                ('Train_No_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Coach', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
